name: "Oppdater url til mikrofrontendmanifest"
on:
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
      id:
        required: true
        type: string
      url:
        required: true
        type: string
      commitmsg:
        required: false
        description: "defaulter til siste innslag i gitlog"
        type: string
jobs:
  trigger_manifest_update:
    runs-on: ubuntu-latest
    env:
      message: ${{ inputs.commitmsg }}
    steps:
      - uses: "actions/checkout@v4"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        name: sett opp python
      - uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          app-id: ${{ secrets.APP_ID }}
      - run : |
          mkdir python
          cd python 
          curl https://raw.githubusercontent.com/navikt/tms-deploy/main/python/requirements.txt >> requirements.txt
          curl https://raw.githubusercontent.com/navikt/tms-deploy/main/python/update_manifest.py >> update_manifest.py
          pip3 install -r requirements.txt
          python3 test_update_manifest.py
        name: Hent oppdateringscript
      - name: Sjekk commitmessage
        if: env.message==''
        run:  |
         echo "message=$(git log -1 --pretty="format:%s")" >> $GITHUB_ENV
      - run: |          
          python3 python/update_manifest.py -id ${{ inputs.id }} -url ${{ inputs.url}} -cluster ${{ inputs.cluster }} -initiator ${{ github.actor }} -message "${{ env.message }}" -token ${{ steps.get-token.outputs.token }}
        name: Oppdater manifest
