name: Validate workflows

on:
  pull_request:
    paths:
      - ".github/workflows/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Validate GitHub Actions workflows
        uses: docker://rhysd/actionlint:1.7.7
        with:
          args: .github/workflows/astro-deploy-v1.yaml
